### ISSUE TITLE
Mysqli_query Error ! 

### ISSUE THREAD

**Issue by HimanshuChandola** [vinitshahdeo/Library-Management-System#1]
Getting this error while logging ! Sir what is the Admin Username And Password... and how to solve this error ! 

![image](https://user-images.githubusercontent.com/34373537/56508722-a7dc7280-6542-11e9-9df2-666744123733.png)

**Comment by vinitshahdeo** [comment]
It seems like you're using xampp with `mysqli`

Try using a stable version of xampp/mamp with msyql support (php<=5.5.x)

**Comment by HimanshuChandola** [comment]
Yepp I used now php 5.5.33 ......... and getting this error 

Fatal error: Call to undefined function mysql_select_db() in C:\xampp\htdocs\library\librarian\dbcon.php on line 2

**Comment by vinitshahdeo** [comment]
Did you change the name of database?

import the database (`eb_lms.sql`) from db folder and configure `dbcon.php` at all places.

**Comment by HimanshuChandola** [comment]
nopes I didn't change the name of database.... it is eb_lms.sql only............  what changes I have to do in dbcon.php?  I checked that file the database name is also same there............
